###
GET http://localhost:8000/api/categories/

###
GET http://localhost:8000/api/categories/3
Accept: application/json


###
POST http://localhost:8000/api/categories/
Content-type: application/json
Accept: application/json

{
    "name": "Categoria 1",
    "description": "Categoria 1"
}



# PUT (Completa) vs PATCH (Parcial)
###
PUT http://localhost:8000/api/categories/4
Content-type: application/json
Accept: application/json

{
    "name": "DimGray",
    "is_active": false
}

###
DELETE http://localhost:8000/api/categories/3
Accept: application/json

# PUT (Completa) vs PATCH (Parcial)
# 200 OK
# 201 Created


###
GET http://localhost:8000/api/videos/

###
GET http://localhost:8000/api/cast-members/e5d20c43-00f5-413a-8636-c4660d572a8e
Accept: application/json


###
POST http://localhost:8000/api/genres/
Content-type: application/json
Accept: application/json

{
    "name": "Genre 1",
    "categories_id" : ["112e6a8d-34ec-4db0-8d5f-68420223e9e3"]
}



# PUT (Completa) vs PATCH (Parcial)
###
PUT http://localhost:8000/api/cast-members/d8d7e510-5ff4-4a7b-9c1a-94f7fa3c9cb9
Content-type: application/json
Accept: application/json

{
    "name": "Drama",
    "is_active": "C"
}

###
DELETE http://localhost:8000/api/cast-members/ff951464-9f69-4de8-9c30-0e80e72c0d63
Accept: application/json


###
GET http://localhost:8000/api/genres/


###
POST http://localhost:8000/api/videos/
Content-type: application/json
Accept: application/json

{
    "title": "Video",
    "description": "descricao descricao",
    "year_launched": 1998,
    "rating": "L",
    "duration": 30,
    "categories_id": ["01a0d23a-dbcd-4952-88a7-91750aed8140"],
    "genres_id": ["0179cb21-7b30-4eb2-ae9a-6277ed99795"]
}



###
PUT http://localhost:8000/api/videos/8ffe5cbd-d416-4f1d-bd52-ced2c0870863
Content-type: application/json
Accept: application/json

{
    "title": "Video",
    "description": "descricao descricao",
    "year_launched": 1999,
    "rating": "L",
    "duration": 30,
    "categories_id": ["03860e8c-3d74-4e8c-bc61-22121bb4058f","07216bc1-9423-4e54-b511-94256aaed1c6"],
    "genres_id": ["04eb23c0-f208-48f1-a632-13a2c45625f3"]
}





###
GET http://localhost:8000/api/genres/


###
POST http://localhost:8000/api/videos/
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Accept: application/json

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="title"

Video
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="description"

descricao descricao
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="year_launched"

1998
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="rating"

L
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="duration"

30
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="categories_id[]"

01a0d23a-dbcd-4952-88a7-91750aed8140
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="genres_id[]"

0179cb21-7b30-4eb2-ae9a-6277ed997956
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="movie_file"; filename="video.mp4"
Content-Type: video/mp4

< ../../../../Pictures/video.mp4
------WebKitFormBoundary7MA4YWxkTrZu0gW--



###
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="movie_file"; filename="video.mp4"
Content-Type: video/mp4

< ../../../../Videos/codeflix/video.mp4
------WebKitFormBoundary7MA4YWxkTrZu0gW--