###
GET http://localhost:8000/api/categories/

###
GET http://localhost:8000/api/categories/0
Accept: application/json


###
POST http://localhost:3000/products
Content-type: application/json

{
    "name": "outro produto",
    "price": 8.99
}



# PUT (Completa) vs PATCH (Parcial)
###
PATCH http://localhost:3000/products/4
Content-type: application/json

{
    "name": "Pão de queijo",
    "price": 9.99
}

###
DELETE http://localhost:3000/products/3

# PUT (Completa) vs PATCH (Parcial)
# 200 OK
# 201 Created