###
GET http://localhost:8000/api/categories/

###
GET http://localhost:8000/api/categories/3
Accept: application/json


###
POST http://localhost:8000/api/categories/
Content-type: application/json
Accept: application/json

{
    "name": "Categoria inativa 3",
    "description": "outra categoria foi desativada 1"
}



# PUT (Completa) vs PATCH (Parcial)
###
PUT http://localhost:8000/api/categories/4
Content-type: application/json
Accept: application/json

{
    "name": "DimGray",
    "is_active": false
}

###
DELETE http://localhost:8000/api/categories/3
Accept: application/json

# PUT (Completa) vs PATCH (Parcial)
# 200 OK
# 201 Created


###
GET http://localhost:8000/api/cast-members/

###
GET http://localhost:8000/api/cast-members/e5d20c43-00f5-413a-8636-c4660d572a8e
Accept: application/json


###
POST http://localhost:8000/api/cast-members/
Content-type: application/json
Accept: application/json

{
    "name": "Leandro2",
    "type": 3
}



# PUT (Completa) vs PATCH (Parcial)
###
PUT http://localhost:8000/api/cast-members/d8d7e510-5ff4-4a7b-9c1a-94f7fa3c9cb9
Content-type: application/json
Accept: application/json

{
    "name": "Drama",
    "is_active": "C"
}

###
DELETE http://localhost:8000/api/cast-members/ff951464-9f69-4de8-9c30-0e80e72c0d63
Accept: application/json
